name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      
      - name: Build APK
        run: |
          flutter create test_app
          cd test_app
          flutter build apk
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: test_app/build/app/outputs/flutter-apk/app-release.apk
